oneup_uploader:
    mappings:
        avatar:
            frontend: dropzone
        logo:
            frontend: dropzone            
        bninefile:
            frontend: dropzone                        